### PR TITLE
Firestore

### PR DESCRIPTION
**Pull request by jannikrh**
Particle and user should be editable.

### CODE REVIEW

**Comment by jannikrh** [comment]
@NotAnsgar Particle and users will be a different branch. This should be merged due to production issues.

**Comment by NotAnsgar** [comment]
I can't add or edit a particle. The plus is not working for me in the preview. Is this content of this PR?

**Comment by jannikrh** [comment]
> I can't add or edit a particle. The plus is not working for me in the preview. Is this content of this PR?

As mentioned in the comment above this will be part of a different branch.

**Review by NotAnsgar — APPROVED** [review]
Looks good to me

**Pull request merged**
